"""v1.7.1 - Add tutorials plugin tables

Revision ID: 8301d822b784
Revises: v1_7_oauth_email_verification
Create Date: 2026-01-12 06:02:22.437332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8301d822b784"
down_revision: Union[str, None] = "v1_7_oauth_email_verification"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutorial_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tutorial_categories_id"),
        "tutorial_categories",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tutorial_categories_name"),
        "tutorial_categories",
        ["name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_tutorial_categories_slug"),
        "tutorial_categories",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "tutorials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column("estimated_time_minutes", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=500), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("completion_count", sa.Integer(), nullable=True),
        sa.Column("xp_reward", sa.Integer(), nullable=True),
        sa.Column("related_skills", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["tutorial_categories.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tutorials_author_id"),
        "tutorials",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tutorials_category_id"),
        "tutorials",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tutorials_created_at"),
        "tutorials",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_tutorials_id"), "tutorials", ["id"], unique=False)
    op.create_index(
        op.f("ix_tutorials_is_published"),
        "tutorials",
        ["is_published"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tutorials_slug"), "tutorials", ["slug"], unique=True
    )
    op.create_index(
        op.f("ix_tutorials_title"), "tutorials", ["title"], unique=False
    )
    op.create_table(
        "tutorial_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tutorial_id", sa.Integer(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("code_example", sa.Text(), nullable=True),
        sa.Column("code_language", sa.String(length=50), nullable=True),
        sa.Column("hints", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tutorial_id"], ["tutorials.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tutorial_steps_id"), "tutorial_steps", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_tutorial_steps_tutorial_id"),
        "tutorial_steps",
        ["tutorial_id"],
        unique=False,
    )
    op.create_table(
        "tutorial_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tutorial_id", sa.Integer(), nullable=False),
        sa.Column("current_step_id", sa.Integer(), nullable=True),
        sa.Column("completed_step_ids", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("time_spent_minutes", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_step_id"], ["tutorial_steps.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tutorial_id"], ["tutorials.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_tutorial_progress_id"),
        "tutorial_progress",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tutorial_progress_tutorial_id"),
        "tutorial_progress",
        ["tutorial_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tutorial_progress_user_id"),
        "tutorial_progress",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tutorial_progress_user_id"), table_name="tutorial_progress"
    )
    op.drop_index(
        op.f("ix_tutorial_progress_tutorial_id"),
        table_name="tutorial_progress",
    )
    op.drop_index(
        op.f("ix_tutorial_progress_id"), table_name="tutorial_progress"
    )
    op.drop_table("tutorial_progress")
    op.drop_index(
        op.f("ix_tutorial_steps_tutorial_id"), table_name="tutorial_steps"
    )
    op.drop_index(op.f("ix_tutorial_steps_id"), table_name="tutorial_steps")
    op.drop_table("tutorial_steps")
    op.drop_index(op.f("ix_tutorials_title"), table_name="tutorials")
    op.drop_index(op.f("ix_tutorials_slug"), table_name="tutorials")
    op.drop_index(op.f("ix_tutorials_is_published"), table_name="tutorials")
    op.drop_index(op.f("ix_tutorials_id"), table_name="tutorials")
    op.drop_index(op.f("ix_tutorials_created_at"), table_name="tutorials")
    op.drop_index(op.f("ix_tutorials_category_id"), table_name="tutorials")
    op.drop_index(op.f("ix_tutorials_author_id"), table_name="tutorials")
    op.drop_table("tutorials")
    op.drop_index(
        op.f("ix_tutorial_categories_slug"), table_name="tutorial_categories"
    )
    op.drop_index(
        op.f("ix_tutorial_categories_name"), table_name="tutorial_categories"
    )
    op.drop_index(
        op.f("ix_tutorial_categories_id"), table_name="tutorial_categories"
    )
    op.drop_table("tutorial_categories")
    # ### end Alembic commands ###
