"""Add navigation and theme tables

Revision ID: 9e92e2da7909
Revises: aff36a560d92
Create Date: 2025-12-04 07:16:34.046608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e92e2da7909'
down_revision: Union[str, None] = 'aff36a560d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('show_in_header', sa.Boolean(), nullable=True),
    sa.Column('show_in_footer', sa.Boolean(), nullable=True),
    sa.Column('target_blank', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_index(op.f('ix_menu_items_order'), 'menu_items', ['order'], unique=False)
    op.create_index(op.f('ix_menu_items_visible'), 'menu_items', ['visible'], unique=False)
    op.create_table('theme_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('background_light', sa.String(length=7), nullable=True),
    sa.Column('background_dark', sa.String(length=7), nullable=True),
    sa.Column('text_light', sa.String(length=7), nullable=True),
    sa.Column('text_dark', sa.String(length=7), nullable=True),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('heading_font', sa.String(length=100), nullable=True),
    sa.Column('font_size_base', sa.String(length=10), nullable=True),
    sa.Column('container_width', sa.String(length=10), nullable=True),
    sa.Column('border_radius', sa.String(length=10), nullable=True),
    sa.Column('custom_css', sa.String(length=10000), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('logo_dark_url', sa.String(length=255), nullable=True),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('advanced_settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme_settings')
    op.drop_index(op.f('ix_menu_items_visible'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_order'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_table('menu_items')
    # ### end Alembic commands ###
